import { ThemeProvider } from 'next-themes';
import './globals.css';
import { NextIntlClientProviderwrapper } from './components/providers/NextIntlClientProvider';
import { getMessages } from "next-intl/server";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const messages = await getMessages();

  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NextIntlClientProviderwrapper messages={{messages}}>
            {children}
          </NextIntlClientProviderwrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
