import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { ThemeProvider } from 'next-themes';
import { NextIntlClientProviderwrapper } from './components/providers/NextIntlClientProvider';
import { getMessages } from "next-intl/server";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
  const messages = await getMessages();
  
  return (
    <html lang="en">
      <body >
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <NextIntlClientProviderwrapper messages={messages}>
            <SessionProvider session={session}>
              {children}
            </SessionProvider>
          </NextIntlClientProviderwrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}


